### ISSUE TITLE
Make “environment” to both sides

### ISSUE THREAD

**Issue by Daniel99j2** [tomalbrc/Sandstorm#1]
Hey, can you change the environment type to “*” or remove it as it means on the client’s dedicated server, the mod does not load. This is problematic for server side mods using sandstorm, in single player worlds.

**Comment by Daniel99j2** [comment]
Also, in the 1.21 version, 1.21.1 is not compatible.

**Comment by tomalbrc** [comment]
Should work on clients and with 1.21.1 now
