### ISSUE TITLE
Emitter Event crash

### ISSUE THREAD

**Issue by Daniel99j2** [tomalbrc/Sandstorm#3]
When using emitter events, the game crashes.
(sorry for all the bug reports, but... yeah)
[crash-2024-11-09_18.58.37-server.txt](https://github.com/user-attachments/files/17686883/crash-2024-11-09_18.58.37-server.txt)

**Comment by tomalbrc** [comment]
Appreciate the reports, will fix it tomorrow

**Comment by tomalbrc** [comment]
Should be fixed in 0.2.0-beta.1
